title: Shree's Portfolio
description: Software Engineer & Cybersecurity Enthusiast
baseurl: ""
url: "https://shreeis.me"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
